# Generated by Django 5.2.3 on 2025-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredientstranslation_master'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='plates', to='ingredients.ingredients'),
        ),
    ]
